name: Deploy SandUI to GitHub Pages

on:
  push:
    branches: [main] # Runs every time you push to main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
          npm run build-storybook # This ensures your docs are built too

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static # This deploys your Storybook docs
          branch: gh-pages # This will CREATE the branch for you automatically